steps:
- name: 'gcr.io/repcore-prod/mvn-deploy:6.0.0'
  secretEnv:
  - GPG_PRIVATE_KEY
  - GPG_PASSPHRASE
  - SONATYPE_USERNAME
  - SONATYPE_TOKEN

availableSecrets:
  secretManager:
  - versionName: projects/repcore-prod/secrets/gpg-private-key/versions/latest
    env: GPG_PRIVATE_KEY
  - versionName: projects/repcore-prod/secrets/gpg-passphrase/versions/latest
    env: GPG_PASSPHRASE
  - versionName: projects/repcore-prod/secrets/sonatype-username/versions/latest
    env: SONATYPE_USERNAME
  - versionName: projects/repcore-prod/secrets/sonatype-token/versions/latest
    env: SONATYPE_TOKEN
